maritimoSampa/maritimoSampa/Controllers/SampaController.cs
using maritimoSampa.Models;
using Microsoft.AspNetCore.Mvc;

namespace maritimoSampa.Controllers
{
    public class SampaController : Controller
    {
        public IActionResult Santos()
        {
            var santos = new List<Municipio>
            {
                new Municipio
                {
                nome = "Santos",
                regiao = "Sul",
                populacao = 418.608,
                desc = "Santos é uma cidade fundamental no cenário econômico " +
                "não apenas de São Paulo, mas de todo o Brasil. Sua importância decorre principalmente do Porto de Santos, " +
                "o maior da América Latina. A cidade é um ponto crucial para importação e exportação, movimentando uma vasta " +
                "gama de produtos, desde commodities agrícolas até produtos manufaturados. Sua localização estratégica e " +
                "infraestrutura portuária de alto nível tornam-na um hub vital para o comércio internacional, " +
                "influenciando diretamente a economia do país.",
                Historia = new List<Historia>{
                new Historia
                {
                resumoHistorico = "A cidade de Santos tornou-se destaque nessas áreas pelos seguintes fatores: Localização Estratégica; " +
                "Infraestrutura Portuária; Capacidade de Movimentação; Tecnologia e Logística; Política e Investimentos; " +
                "Diversificação de Atividades"
                }
                },

                Produto = new List<Produto>{
                new Produto
                {
                nome = "Soja",
                categoria = "Produto Agrícola",
                descp = "A soja é essencialmente uma espécie autógama, ou seja, uma planta polinizada por ela mesma e não " +
                "por outras plantas, mesmo que vizinhas a ela, com flores perfeitas e órgãos masculinos e femininos protegidos " +
                "dentro da corola"
                }
                },
            }
            };

            ViewBag.nome = santos[0].nome;
            return View(santos);

        }
        public IActionResult Guaruja()
        {
            var guaruja = new List<Municipio>
            {
            new Municipio
            {
                nome = "Guarujá",
                regiao = "Sul",
                populacao = 322.750,
                desc = "Guarujá, localizado no litoral do estado de São Paulo, tem uma significativa influência na economia de " +
            "exportação e importação do Brasil, principalmente devido à sua proximidade com o Porto de Santos, o maior porto " +
            "da América Latina. Em resumo, Guarujá, através do Porto de Santos, desempenha um " +
            "papel vital na economia de exportação e importação do Brasil, contribuindo significativamente para o comércio " +
            "internacional, geração de empregos e desenvolvimento econômico regional.",
            Historia = new List<Historia>{
                new Historia
                {
                resumoHistorico = "Guarujá tornou-se um destaque no cenário de exportação e importação principalmente devido ao " +
                "desenvolvimento e à modernização do Porto de Santos, que é uma infraestrutura fundamental para a logística e o " +
                "comércio exterior do Brasil.São Sebastião tornou-se um destaque no quesito exportação principalmente devido ao " +
                "desenvolvimento estratégico do Terminal Marítimo Almirante Barroso (TEBAR), operado pela Transpetro, uma " +
                "subsidiária da Petrobras."
                }
                },

                Produto = new List<Produto>{
                new Produto
                {
                nome = "Café",
                categoria = "Produto Agrícola",
                descp = "O café é uma das bebidas mais apreciadas em todo o planeta e é produzido dos grãos de café, a semente " +
                "do fruto do cafeeiro. O cafeeiro é uma espécie originária da Etiópia que se difundiu por todo o mundo."
                }
                },
            }
            };
            ViewBag.nome = guaruja[0].nome;
            return View(guaruja);
        }
        public IActionResult SaoSebastiao()
        {
            var ssebastiao = new List<Municipio>
            {
            new Municipio
            {
                nome = "São Sebastião",
                regiao = "Norte",
                populacao = 90.328,
                desc = "São Sebastião, através do seu porto, tem uma influência significativa na economia de exportação e " +
            "importação do Brasil, especialmente no setor de petróleo e produtos químicos. Embora não tão grande quanto o " +
            "Porto de Santos, o Porto de São ,Sebastião desempenha um papel crucial em certos segmentos, contribuindo para " +
            "a economia regional e nacional por meio da geração de empregos, arrecadação de receitas e apoio à " +
            "infraestrutura local.",
            Historia = new List<Historia>{
                new Historia
                {
                resumoHistorico = "São Sebastião tornou-se um destaque no quesito exportação principalmente devido ao " +
                "desenvolvimento estratégico do Terminal Marítimo Almirante Barroso (TEBAR), operado pela Transpetro, uma " +
                "subsidiária da Petrobras."
                }
                },

                Produto = new List<Produto>{
                new Produto
                {
                nome = "Petróleo",
                categoria = "Recurso Fóssil",
                descp = "O petróleo é um líquido natural, inflamável, oleoso, de cheiro característico e com densidade menor " +
                "que a da água. É uma mistura complexa de hidrocarbonetos, ou seja, de substâncias formadas apenas por " +
                "hidrogênio e carbono."
                }
                },
            }
            };
            ViewBag.nome = ssebastiao[0].nome;
            return View(ssebastiao);
        }
        public IActionResult Itanhaem()
        {
            var itanhaem = new List<Municipio>
            {
            new Municipio
            {
                nome = "Itanhaém",
                regiao = "Sul",
                populacao = 103.102,
                desc = "Itanhaém, apesar de não ser um grande centro de exportação e importação, tem uma influência indireta na " +
            "economia regional graças à sua proximidade com o Porto de Santos e ao turismo local. A cidade pode explorar " +
            "oportunidades para desenvolver sua ,infraestrutura logística e comercial, potencialmente aumentando sua " +
            "participação no comércio exterior. Contudo, a falta de um porto comercial próprio limita a influência direta " +
            "de Itanhaém na economia de exportação e importação do Brasil.",
            Historia = new List<Historia>{
                new Historia
                {
                resumoHistorico = "Itanhaém, embora não seja um grande centro de importação e exportação como Santos ou São " +
                "Sebastião, tem se destacado de maneira mais indireta no cenário econômico regional."
                }
                },

                Produto = new List<Produto>{
                new Produto
                {
                nome = "Pescados e Produtos Agrícolas",
                categoria = "Produto Agrícola e Pesqueiro",
                descp = "Produtos agrícolas são alimentos e commodities cultivados na agricultura, como grãos, frutas, legumes " +
                "e verduras, enquanto os pescados são alimentos obtidos da pesca, incluindo peixes, crustáceos e moluscos."
                }
                },
            }
            };
            ViewBag.nome = itanhaem[0].nome;
            return View(itanhaem);

    }   }
}

maritimoSampa/maritimoSampa/Views/Sampa/Guaruja.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = null;
}
@model IEnumerable<Municipio>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/css/cidade.css" asp-append-version="true" />
</head>
<body>

    <header class="header">
        <a class="navbar-brand" asp-area="" asp-controller="Sampa" asp-action="Santos"><img src="~/img/seta-esquerda.png" class="header-image" /></a>
        <h1 class="header-text">@ViewBag.nome</h1>
        <a class="navbar-brand" asp-area="" asp-controller="Sampa" asp-action="SaoSebastiao"><img src="~/img/seta-direita.png" class="header-image" /></a>
    </header>


    <div class="center">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img class="home" src="~/img/home.png" alt="home" /></a>
        <a class="navbar-brand" href="https://maps.app.goo.gl/akZQ6u5k2fJcLgjw8"><img class="home" src="~/img/maps.png" alt="home" /></a>
    </div>
    @foreach (var guaruja in Model)
    {

        <div class="container">

            <div class="init">
                <div class="part1">
                    <p>
                        @guaruja.desc
                    </p>
                </div>
                <div class="imgpart"><img class="imgpartimg" src="~/img/guaru.jpg" /></div>
            </div>

        </div>

        <div class="final">
            <div class="finalimg"><img class="finalimgimg" src="~/img/guaruja.jpg" /></div>

            <div class="finaltext">
                <p class="finalp">
                    @foreach (var Historia in guaruja.Historia)
                    {
                        @Historia.resumoHistorico
                    }
                </p>
            </div>

        </div>

        <div class="final2">
            <div class="finalimg"><img class="finalimgimg" src="~/img/cafe.webp" /></div>

            <div class="finaltext">
                <p class="finalp">
                    @foreach (var Produto in guaruja.Produto)
                    {
                        @Produto.descp
                    }
                </p>
            </div>
        </div>

        <script src="~/js/site.js" asp-append-version="true"></script>
    }
</body>
</html>

maritimoSampa/maritimoSampa/Views/Sampa/Itanhaem.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = null;
}
@model IEnumerable<Municipio>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/css/cidade.css" asp-append-version="true" />
</head>
<body>

    <header class="header">
        <a class="navbar-brand" asp-area="" asp-controller="Sampa" asp-action="SaoSebastiao"><img src="~/img/seta-esquerda.png" class="header-image" /></a>
        <h1 class="header-text">@ViewBag.nome</h1>
        <a class="navbar-brand" asp-area="" asp-controller="Sampa" asp-action="Santos"><img src="~/img/seta-direita.png" class="header-image" /></a>
    </header>


    <div class="center">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img class="home" src="~/img/home.png" alt="home" /></a>
        <a class="navbar-brand" href="https://maps.app.goo.gl/r56fcgZni7C1Aixz9"><img class="home" src="~/img/maps.png" alt="home" /></a>
    </div>
    @foreach (var itanhaem in Model)
    {

        <div class="container">

            <div class="init">
                <div class="part1">
                    <p>
                        @itanhaem.desc
                    </p>
                </div>
                <div class="imgpart"><img class="imgpartimg" src="~/img/itan.jpg" /></div>
            </div>

        </div>

        <div class="final">
            <div class="finalimg"><img class="finalimgimg" src="~/img/itanhaem.jpg" /></div>

            <div class="finaltext">
                <p class="finalp">
                    @foreach (var Historia in itanhaem.Historia)
                    {
                        @Historia.resumoHistorico
                    }
                </p>
            </div>

        </div>

        <div class="final2">
            <div class="finalimg"><img class="finalimgimg" src="~/img/pescados.png" /></div>

            <div class="finaltext">
                <p class="finalp">
                    @foreach (var Produto in itanhaem.Produto)
                    {
                        @Produto.descp
                    }
                </p>
            </div>
        </div>

        <script src="~/js/site.js" asp-append-version="true"></script>
    }
</body>
</html>

maritimoSampa/maritimoSampa/Views/Sampa/Santos.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = null;
}
@model IEnumerable<Municipio>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/css/cidade.css" asp-append-version="true" />
</head>
<body>

    <header class="header">
        <a class="navbar-brand" asp-area="" asp-controller="Sampa" asp-action="Itanhaem"><img src="~/img/seta-esquerda.png" class="header-image" /></a>
        <h1 class="header-text">@ViewBag.nome</h1>
        <a class="navbar-brand" asp-area="" asp-controller="Sampa" asp-action="Guaruja"><img src="~/img/seta-direita.png" class="header-image" /></a>
    </header>


    <div class="center">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img class="home" src="~/img/home.png" alt="home" /></a>
        <a class="navbar-brand" href="https://maps.app.goo.gl/CrdsYb75rJt7uXQJ9"><img class="home" src="~/img/maps.png" alt="home" /></a>
    </div>
    @foreach (var santos in Model)
    {
        <div class="container">

            <div class="init">
                <div class="part1">
                    <p>

                        @santos.desc


                    </p>
                </div>
                <div class="imgpart"><img class="imgpartimg" src="~/img/san.jpg" /></div>
            </div>

        </div>

        <div class="final">
            <div class="finalimg"><img class="finalimgimg" src="~/img/santos.jpg" /></div>

            <div class="finaltext">
                <p class="finalp">
                    @foreach (var Historia in santos.Historia)
                    {
                        @Historia.resumoHistorico
                    }
                </p>
            </div>

        </div>

        <div class="final2">
            <div class="finalimg"><img class="finalimgimg" src="~/img/soja.webp" /></div>

            <div class="finaltext">
                <p class="finalp">
                    @foreach (var Produto in santos.Produto)
                    {
                        @Produto.descp
                    }
                </p>
            </div>
        </div>


        <script src="~/js/site.js" asp-append-version="true"></script>
    }
</body>
</html>

maritimoSampa/maritimoSampa/Views/Sampa/SaoSebastiao.cshtml
@{
    Layout = null;
}
@model IEnumerable<Municipio>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="~/css/cidade.css" asp-append-version="true" />
</head>
<body>

    <header class="header">
        <a class="navbar-brand" asp-area="" asp-controller="Sampa" asp-action="Guaruja"><img src="~/img/seta-esquerda.png" class="header-image" /></a>
        <h1 class="header-text">@ViewBag.nome</h1>
        <a class="navbar-brand" asp-area="" asp-controller="Sampa" asp-action="Itanhaem"><img src="~/img/seta-direita.png" class="header-image" /></a>
    </header>


    <div class="center">
        <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img class="home" src="~/img/home.png" alt="home" /></a>
        <a class="navbar-brand" href="https://maps.app.goo.gl/tqUi5A2CQESYuhz67"><img class="home" src="~/img/maps.png" alt="home" /></a>
    </div>
    @foreach (var ssebastiao in Model)
    {

        <div class="container">

            <div class="init">
                <div class="part1">
                    <p>
                        @ssebastiao.desc
                    </p>
                </div>
                <div class="imgpart"><img class="imgpartimg" src="~/img/sebas.jpg" /></div>
            </div>

        </div>

        <div class="final">
            <div class="finalimg"><img class="finalimgimg" src="~/img/saosebastiao.jpg" /></div>

            <div class="finaltext">
                <p class="finalp">
                    @foreach (var Historia in ssebastiao.Historia)
                    {
                        @Historia.resumoHistorico
                    }
                </p>
            </div>

        </div>

        <div class="final2">
            <div class="finalimg"><img class="finalimgimg" src="~/img/Petroleo.jpg" /></div>

            <div class="finaltext">
                <p class="finalp">
                    @foreach (var Produto in ssebastiao.Produto)
                    {
                        @Produto.descp
                    }
                </p>
            </div>
        </div>

        <script src="~/js/site.js" asp-append-version="true"></script>
    }
</body>
</html>